version: '3.9'

services:
  medstock:
    container_name: medstock
    image: postgres:16
    ports:
      - 4848:5432
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: medstock_admin
    volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}